#!/usr/bin/env python3
"""Build a whole walkthrough page from a JSON spec.

The mode and feature pages all tell the same shape of story — find it, set it
up, watch it run, score it, read the result — over a different set of
screenshots. Hand-assembling sixteen of those means sixteen chances to forget a
lazy hint, mistype a path, or let the nav drift out of step with the sections.
So the spec carries the words and the screenshot names, and this writes the
page. Sections come from build-guide-section.py.

    python3 tools/build-guide-page.py tools/specs/doghouse.json
    python3 tools/build-guide-page.py tools/specs/*.json      # all of them

Each spec names its output, so a page is regenerated by re-running its spec.
Anything hand-written on a page will be overwritten — edit the spec instead.
"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import importlib
_sec = importlib.import_module('build-guide-section')

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

HEAD = '''<!DOCTYPE html>
<!--
  Generated by tools/build-guide-page.py from tools/specs/{slug}.json — edit the
  spec, not this file. Screenshots come from the set the app generates; re-import
  them with tools/import-guide-shots.py.
-->
<html lang="en" data-i18n-base="{up}" data-i18n-title="page.{i18n_page}.title">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>{title} – TournaQ</title>
  <link rel="icon" href="{up}favicon.ico" sizes="any">
  <link rel="icon" type="image/png" sizes="32x32" href="{up}assets/favicon-32.png">
  <link rel="icon" type="image/png" sizes="16x16" href="{up}assets/favicon-16.png">
  <link rel="apple-touch-icon" href="{up}apple-touch-icon.png">
  <link rel="manifest" href="{up}site.webmanifest">
  <meta name="theme-color" content="#3A3E16">
  <link rel="stylesheet" href="{up}css/style.css">
  <script src="{up}js/main-nav.js" defer></script>
  <script src="{up}js/i18n.js" defer></script>
  <script src="{up}js/feature-subnav.js" defer></script>
</head>

<body>

  <header>
    <nav class="nav">
      <a class="logo" href="{home}">
        <img src="{up}assets/brand/tournaq-logo-land-450.webp" alt="TournaQ" width="225" height="150" loading="eager" decoding="async">
      </a>
      <input type="checkbox" id="nav-toggle" class="nav-toggle" aria-label="Toggle navigation">
      <label for="nav-toggle" class="nav-burger" aria-label="Open navigation menu">
        <span></span><span></span><span></span>
      </label>
      <div id="main-nav-links"></div>
      <div class="lang-switcher"></div>
    </nav>

    <div class="lang-switcher"></div>

    <div class="hero">
      <h1>{title}</h1>
      <p class="subtitle">{subtitle}</p>
    </div>
  </header>

  <main>

    <div id="feature-subnav"></div>

'''

FOOT = '''    <div class="feedback-cta">
      <div class="feedback-cta-text">
        <strong data-i18n="feedback.cta.title">Questions or Feedback?</strong>
        <p data-i18n="{feedback_key}">{feedback}</p>
      </div>
      <a href="{contact}" class="feedback-cta-btn" data-i18n="feedback.cta.btn">Get in Touch</a>
    </div>

  </main>

  <footer>
    <p data-i18n="footer.copyright">© 2026 Martin Adam · TournaQ</p>
    <p>
      <a href="{home}" data-i18n="footer.home">Home</a> &nbsp;·&nbsp;
      <a href="{legal}" data-i18n="footer.legalHub">Legal Hub</a> &nbsp;·&nbsp;
      <a href="{contact}" data-i18n="footer.contact">Contact</a>
    </p>
  </footer>

</body>

</html>
'''

# Status badges reuse features.pill.*, which is already translated in all three
# locales — so a mode going live does not need a new German or Spanish string.
BADGES = {
    'available': ('completed-status phase-status', 'features.pill.available', 'Available'),
    'planned': ('planned-status status-badge', 'features.pill.planned', 'Planned'),
}


def lead_card(spec, depth):
    up = '../' * depth
    out = ['    <!-- Overview -->', '    <section class="card">']

    if spec.get('status'):
        cls, key, label = BADGES[spec['status']]
        out.append('      <div class="%s" data-i18n="%s">%s</div>' % (cls, key, label))
    out.append('      <h2>%s</h2>' % spec['title'])
    out.append('')

    hero = spec.get('hero')
    copy = []
    for para in spec.get('intro', []):
        copy.append('          <p>%s</p>' % para)
    if spec.get('bestfor'):
        copy.append('          <h3 style="color: var(--olive-dark); margin: 22px 0 10px;">Best for</h3>')
        copy.append('          <ul style="padding-left: 20px; line-height: 1.9; font-size: 14px; margin-bottom: 0;">')
        for item in spec['bestfor']:
            copy.append('            <li>%s</li>' % item)
        copy.append('          </ul>')
    if spec.get('sections'):
        copy.append('')
        copy.append('          <div class="card-nav" style="margin-bottom: 0;">')
        copy.append('            <div class="card-nav-label">Jump to section</div>')
        copy.append('            <div class="card-nav-links">')
        for sec in spec['sections']:
            copy.append('              <a href="#%s">%s</a>' % (sec['id'], sec.get('nav', sec['title'])))
        if spec.get('workflow'):
            copy.append('              <a href="#workflow">Workflow</a>')
        copy.append('            </div>')
        copy.append('          </div>')

    if hero:
        out.append('      <div class="guide-split is-lead" style="margin-top: 22px;">')
        out.append('        <div class="split-media">')
        if hero.get('image'):
            out.append('          <img src="%s%s"' % (up, hero['image']))
            out.append('               sizes="(max-width: 760px) 90vw, 260px"')
            out.append('               width="%d" height="%d"' % (hero['w'], hero['h']))
            out.append('               loading="eager" fetchpriority="high" decoding="async"')
            out.append('               style="width:100%; border-radius:14px; border:1px solid var(--border);"')
            out.append('               alt="%s">' % hero['alt'])
        else:
            # same rule as the section cards: a bare name belongs to this page's
            # own folder, a slash means it comes from somewhere else
            rel = hero['shot']
            if '/' not in rel:
                rel = '%s/%s' % (spec.get('folder', ''), rel)
            out.append(_sec.shot_markup(rel, depth, hero['alt'], False, 10,
                                        sizes='(max-width: 760px) 90vw, 260px'))
        out.append('        </div>')
        out.append('        <div class="split-copy">')
        out.extend(copy)
        out.append('        </div>')
        out.append('      </div>')
    else:
        out.extend(line[2:] if line.startswith('  ') else line for line in copy)

    out.append('    </section>')
    out.append('')
    return '\n'.join(out)


def preserved(spec):
    """Lift the existing <ul class="feature-list"> off a page being rebuilt.

    Those lists carry i18n keys and, on some pages, wording generated from the
    feature matrix. Rewriting them by hand would drop the German and Spanish and
    let the matrix and the page drift apart, so they are moved across intact.
    """
    src = spec.get('keep_feature_list')
    if not src:
        return ''
    html = open(os.path.join(REPO, src), encoding='utf-8').read()
    start = html.find('<ul class="feature-list">')
    if start < 0:
        raise SystemExit('no feature-list found in ' + src)
    end = html.index('</ul>', start) + len('</ul>')
    body = html[start:end]

    title = spec.get('feature_list_title', 'Every feature on this page')
    text = spec.get('feature_list_text', '')
    out = ['    <!-- Feature list (preserved from the previous page) -->',
           '    <section id="features" style="margin-top: 40px;">',
           '      <h2 class="section-title">%s</h2>' % title]
    if text:
        out.append('      <p class="section-text">%s</p>' % text)
    out.append('')
    out.append('\n'.join('      ' + ln.strip() if ln.strip() else ln
                          for ln in body.split('\n')))
    out += ['    </section>', '']
    return '\n'.join(out)


def workflow(spec):
    if not spec.get('workflow'):
        return ''
    out = ['    <!-- Workflow -->',
           '    <section id="workflow" style="margin-top: 40px;">',
           '      <h2 class="section-title">%s</h2>' % spec.get('workflow_title', 'Start to finish'),
           '      <div class="workflow-card">',
           '        <ol style="padding-left: 22px; color: var(--muted); line-height: 1.9; font-size: 14px;">']
    for step in spec['workflow']:
        out.append('          <li>%s</li>' % step)
    out += ['        </ol>', '      </div>', '    </section>', '']
    return '\n'.join(out)


def build(path):
    spec = json.load(open(path, encoding='utf-8'))
    depth = spec.get('depth', 2)
    up = '../' * depth
    ctx = {
        'slug': spec['slug'],
        'up': up,
        'home': up + 'pages/index.html' if depth > 1 else 'index.html',
        'contact': up + 'pages/contact.html' if depth > 1 else 'contact.html',
        'legal': up + 'pages/legal.html' if depth > 1 else 'legal.html',
        'title': spec['title'],
        'subtitle': spec['subtitle'],
        'i18n_page': spec.get('i18n_page', 'modes.' + spec['slug']),
        'feedback': spec.get('feedback',
                             'Spotted something missing, or want to suggest an improvement?'),
        # these keys already exist for the pages that had them; a missing one
        # just falls back to the English written inline
        'feedback_key': spec.get('feedback_key',
                                 '%s.feedback.text' % spec.get('i18n_page', 'modes.' + spec['slug'])),
    }
    # pages under pages/modes/ and pages/features/ link up one level to siblings
    if depth == 2:
        ctx['home'] = '../index.html'
        ctx['contact'] = '../contact.html'
        ctx['legal'] = '../legal.html'

    body = HEAD.format(**ctx) + lead_card(spec, depth)
    body += _sec.render(spec) + preserved(spec) + workflow(spec) + FOOT.format(**ctx)

    out_path = os.path.join(REPO, spec['out'])
    open(out_path, 'w', encoding='utf-8').write(body)
    n_shots = body.count('<img ')
    print('  %-46s %d sections, %d images' % (spec['out'], len(spec.get('sections', [])), n_shots))


def main():
    if len(sys.argv) < 2:
        sys.exit('usage: build-guide-page.py spec.json [spec.json ...]')
    for p in sys.argv[1:]:
        build(p)


if __name__ == '__main__':
    main()
